// --------------[ DO NOT EDIT ]--------------
//  THIS IS AN AUTOMATICALLY GENERATED FILE
//  EDIT:
//    scripts/codegen/create_fortran_kernel_interface.py
// ===========================================

#include <occa/c/kernel_fortran_interface.h>
#include <occa/c/kernel.h>

OCCA_START_EXTERN_C

void occaKernelRunF01(occaKernel kernel,
                      const int argc,
                      occaType arg01) {
  occaKernelRunN(kernel, argc,
                 arg01);
}

void occaKernelRunF02(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02);
}

void occaKernelRunF03(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03);
}

void occaKernelRunF04(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04);
}

void occaKernelRunF05(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05);
}

void occaKernelRunF06(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06);
}

void occaKernelRunF07(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07);
}

void occaKernelRunF08(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08);
}

void occaKernelRunF09(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09);
}

void occaKernelRunF10(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10);
}

void occaKernelRunF11(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11);
}

void occaKernelRunF12(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12);
}

void occaKernelRunF13(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13);
}

void occaKernelRunF14(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14);
}

void occaKernelRunF15(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15);
}

void occaKernelRunF16(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15,
                      occaType arg16) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15,
                 arg16);
}

void occaKernelRunF17(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15,
                      occaType arg16,
                      occaType arg17) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15,
                 arg16,
                 arg17);
}

void occaKernelRunF18(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15,
                      occaType arg16,
                      occaType arg17,
                      occaType arg18) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15,
                 arg16,
                 arg17,
                 arg18);
}

void occaKernelRunF19(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15,
                      occaType arg16,
                      occaType arg17,
                      occaType arg18,
                      occaType arg19) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15,
                 arg16,
                 arg17,
                 arg18,
                 arg19);
}

void occaKernelRunF20(occaKernel kernel,
                      const int argc,
                      occaType arg01,
                      occaType arg02,
                      occaType arg03,
                      occaType arg04,
                      occaType arg05,
                      occaType arg06,
                      occaType arg07,
                      occaType arg08,
                      occaType arg09,
                      occaType arg10,
                      occaType arg11,
                      occaType arg12,
                      occaType arg13,
                      occaType arg14,
                      occaType arg15,
                      occaType arg16,
                      occaType arg17,
                      occaType arg18,
                      occaType arg19,
                      occaType arg20) {
  occaKernelRunN(kernel, argc,
                 arg01,
                 arg02,
                 arg03,
                 arg04,
                 arg05,
                 arg06,
                 arg07,
                 arg08,
                 arg09,
                 arg10,
                 arg11,
                 arg12,
                 arg13,
                 arg14,
                 arg15,
                 arg16,
                 arg17,
                 arg18,
                 arg19,
                 arg20);
}

OCCA_END_EXTERN_C
