#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2014-2018 David Medina and Tim Warburton
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

TEST_DIR=$(dirname "$0")

export ASAN_OPTIONS
ASAN_OPTIONS+=':protect_shadow_gap=0'
ASAN_OPTIONS+=':detect_container_overflow=0'

HEADER_CHARS=80

tests_cpp=$(find "${TEST_DIR}" -type f -name '*.cpp')
for test_cpp in ${tests_cpp}; do
    test="${test_cpp/${TEST_DIR}/${TEST_DIR}/bin}"
    test="${test/\.cpp/}"

    # Test output header
    test_name="${test_cpp/${TEST_DIR}\//}"
    chars=$(echo "${test_name}" | wc -c);
    linechars=$((${HEADER_CHARS} - ${chars} - 6));
	  line=$(printf '%*s' ${linechars} | tr ' ' '-');
	  echo -e "\n---[ ${test_name} ]${line}";

    # Make sure not to go over the log size
    if [ -n "${TRAVIS}" ]; then
	      "${test}" 2>&1 | head -n 100;
    else
        "${test}"
    fi

    # Test output footer
	  printf '%*s\n' ${HEADER_CHARS} | tr ' ' '=';
done
