if (APPLE)
  find_library(METAL_LIBRARY Metal)
  find_library(CORE_SERVICES CoreServices)
  find_library(APP_KIT AppKit)
endif()

if (METAL_LIBRARY AND CORE_SERVICES AND APP_KIT)
  set(WITH_METAL 1)
  set(OCCA_METAL_ENABLED 1)
endif()
