message("Configuration summary")
message("  System:                       ${CMAKE_SYSTEM}")
message("  CXX compiler:                 ${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_ID})")
message("  CXX FLAGS:                    ${CMAKE_CXX_FLAGS}")
message("  C compiler:                   ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID})")
message("  C FLAGS:                      ${CMAKE_C_FLAGS}\n")

if (CUDA_FOUND)
  message("  With CUDA:                    ON")
  message("    CUDA version:               ${CUDA_VERSION_STRING}")
  message("    CUDA include dirs:          ${CUDA_INCLUDE_DIRS}")
  message("    CUDA libraries:             ${CUDA_LIBRARIES}")
else()
  message("  With CUDA:                    OFF")
endif()

if (MPI_FOUND)
  message("  With MPI:                     ON")
  message("    MPI version:                ${MPI_CXX_VERSION}")
  message("    MPI include dirs:           ${MPI_CXX_INCLUDE_DIRS}")
  message("    MPI libraries:              ${MPI_CXX_LIBRARIES}")
  message("    MPI link flags:             ${MPI_CXX_LINK_FLAGS}")

else()
  message("  With MPI:                     OFF")
endif()

if (OpenMP_FOUND)
  message("  With OpenMP:                  ON")
  message("    OpenMP version:             ${OpenMP_CXX_VERSION}")
  message("    OpenMP flags:               ${OpenMP_CXX_FLAGS}")
  message("    OpenMP include dirs:        ${OpenMP_CXX_INCLUDE_DIRS}")
  message("    OpenMP libraries:           ${OpenMP_CXX_LIBRARIES}")
else()
  message("  With OpenMP:                  OFF")
endif()

if (OpenCL_FOUND)
  message("  With OpenCL:                  ON")
  message("    OpenCL version:             ${OpenCL_VERSION_STRING}")
  message("    OpenCL include dirs:        ${OpenCL_INCLUDE_DIRS}")
  message("    OpenCL libraries:           ${OpenCL_LIBRARIES}")
else()
  message("  With OpenCL:                  OFF")
endif()

if (WITH_METAL)
  message("  With Metal:                   ON")
else()
  message("  With Metal:                   OFF")
endif()

if (HIP_FOUND)
  message("  With HIP:                     ON")
  message("    HIP version:                ${HIP_VERSION_STRING}")
  message("    HIP platform:               ${HIP_PLATFORM}")
  message("    HIP include dirs:           ${HIP_INCLUDE_DIRS}")
  message("    HIP libraries:              ${HIP_LIBRARIES}")
else()
  message("  With HIP:                     OFF")
endif()

message("\n")
